### ISSUE TITLE
Unable to Start Server

### ISSUE THREAD

**Issue by surrenderoz** [opengsn/workshop#4]
![image](https://user-images.githubusercontent.com/62333368/183932404-85ba6a6a-9e16-42d1-8fb7-2d6650007f31.png)

**Comment by pthor11** [comment]
Me too

**Comment by web3dopamine** [comment]
you need to do `truffle init`

the read me file need some elaboration

**Comment by ivanmmurciaua** [comment]
Install truffle or create a `truffle-config.js` file

**Comment by 14041999ai** [comment]
Install truffle and use "truffle int"
Make sure you have all the files in your local repository I had to manually copy the file.

**Comment by pthor11** [comment]
> Install truffle or create a `truffle-config.js` file

Thanks!!
